[versions]
junit = "4.13.2"
coreTesting = "2.2.0"
fragmentTesting = "1.6.2"
espressoCore = "3.4.0"
extJunit = "1.1.3"
testCore = "1.4.0"
testRunner = "1.4.0"
testRules = "1.4.0"
agp = "8.10.0"
junitVersion = "1.2.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
retrofit = "2.9.0"
recyclerview = "1.4.0"
kotlin = "1.9.23"
coreKtx = "1.15.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTesting" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragmentTesting" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
